version: "3.7"
services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube_container
    depends_on:
      - db
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  init:
    image: bash
    privileged: true
    user: root
    networks:
      - sonarnet
    volumes:
      - ./init.sh:/mnt/init.sh
    command: [ "sh", "-e", "/mnt/init.sh" ]
  db:
    image: postgres:12
    container_name: sonar_postgres
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonar_postgres:/var/lib/postgresql
      - sonar_postgres_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  sonar_postgres:
  sonar_postgres_data:
